apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 034768441662.dkr.ecr.ap-south-1.amazonaws.com/chatapp-backend:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: chatapp-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: JWT_SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: MONGODB_URI
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
