apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
stringData:
  MONGO_USERNAME: mongoadmin
  MONGO_PASSWORD: 1b2282dab4cd946e9b3ca17304d1381e
  JWT_SECRET: eqIlHryfBp2N/bF5fZVROJOltc5+ci5Kqc9ML/K2Hd4N3VPI2dmb4MMkIbEtMufM
  MONGODB_URI: mongodb://mongoadmin:1b2282dab4cd946e9b3ca17304d1381e@mongodb:27017/chatapp?authSource=admin
