apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JyothiKumar37/Full_Stack_Chatapp_CICD.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: chatapp
  syncPolicy:
    automated:
      prune: true      # delete resources removed from Git
      selfHeal: true   # revert manual kubectl changes back to Git state
    syncOptions:
      - CreateNamespace=true
